spring:
  datasource:
    url: jdbc:postgresql://192.168.1.33:5432/blog
    username: postgres
    password: postgres

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog.master.xml
server:
  port: 9000